dist: trusty
addons:
  chrome: stable
jdk:
  - oraclejdk8
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
script: "./travis-build.sh"